set_property IOSTANDARD LVCMOS33 [get_ports led_1]
set_property PACKAGE_PIN R26 [get_ports led_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_2]
set_property PACKAGE_PIN P26 [get_ports led_2]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN F22 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN U26 [get_ports sys_rst_n]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RPi_GPIO_OUT[0]}]
set_property PACKAGE_PIN C12 [get_ports {RPi_GPIO_OUT[0]}]
set_property PACKAGE_PIN B11 [get_ports {RPi_GPIO_OUT[1]}]
set_property PACKAGE_PIN C18 [get_ports {RPi_GPIO_OUT[2]}]
set_property PACKAGE_PIN D18 [get_ports {RPi_GPIO_OUT[3]}]
set_property PACKAGE_PIN E18 [get_ports {RPi_GPIO_OUT[4]}]
set_property PACKAGE_PIN C11 [get_ports {RPi_GPIO_OUT[5]}]
set_property PACKAGE_PIN D10 [get_ports {RPi_GPIO_OUT[6]}]
set_property PACKAGE_PIN B12 [get_ports {RPi_GPIO_OUT[7]}]
set_property PACKAGE_PIN A12 [get_ports {RPi_GPIO_OUT[8]}]
set_property PACKAGE_PIN D14 [get_ports {RPi_GPIO_OUT[9]}]
set_property PACKAGE_PIN C13 [get_ports {RPi_GPIO_OUT[10]}]
set_property PACKAGE_PIN D13 [get_ports {RPi_GPIO_OUT[11]}]
set_property PACKAGE_PIN A10 [get_ports {RPi_GPIO_OUT[12]}]
set_property PACKAGE_PIN E10 [get_ports {RPi_GPIO_OUT[13]}]
set_property PACKAGE_PIN C17 [get_ports {RPi_GPIO_OUT[14]}]
set_property PACKAGE_PIN A15 [get_ports {RPi_GPIO_OUT[15]}]
set_property PACKAGE_PIN B10 [get_ports {RPi_GPIO_OUT[16]}]
set_property PACKAGE_PIN D16 [get_ports {RPi_GPIO_OUT[17]}]
set_property PACKAGE_PIN B15 [get_ports {RPi_GPIO_OUT[18]}]
set_property PACKAGE_PIN B9 [get_ports {RPi_GPIO_OUT[19]}]
set_property PACKAGE_PIN A9 [get_ports {RPi_GPIO_OUT[20]}]
set_property PACKAGE_PIN A8 [get_ports {RPi_GPIO_OUT[21]}]
set_property PACKAGE_PIN C14 [get_ports {RPi_GPIO_OUT[22]}]
set_property PACKAGE_PIN A14 [get_ports {RPi_GPIO_OUT[23]}]
set_property PACKAGE_PIN B14 [get_ports {RPi_GPIO_OUT[24]}]
set_property PACKAGE_PIN A13 [get_ports {RPi_GPIO_OUT[25]}]
set_property PACKAGE_PIN C9 [get_ports {RPi_GPIO_OUT[26]}]
set_property PACKAGE_PIN D15 [get_ports {RPi_GPIO_OUT[27]}]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]